### ISSUE TITLE
Plugin Crashes

### ISSUE THREAD

**Issue by KiyoIchikawa** [SepehrImanian/terraform-provider-haproxy#3]
### Prerequisites

- Be sure that there's no open issue already.

### Description

We are trying to use the plugin in a module and getting a hard crash. Our Terraform code layout is like this:

```
.
|__ README.md
|__ modules/
|     |__ module1/
|            |__ README.md
|            |__ versions.tf
|            |__ providers.tf
|            |__ variables.tf
|            |__ main.tf
|            |__ outputs.tf
|     |__ module2/
|            |__ README.md
|            |__ versions.tf
|            |__ providers.tf
|            |__ variables.tf
|            |__ main.tf
|            |__ outputs.tf
|__ development/
|    |__ appA/
|            |__ README.md
|            |__ main.tf
|            |__ versions.tf
|            |__ variables.tf
|__ stage/
|    |__ appA/
|            |__ README.md
|            |__ main.tf
|            |__ versions.tf
|            |__ variables.tf
|__ production/
|    |__ appA/
|            |__ README.md
|            |__ main.tf
|            |__ versions.tf
|            |__ variables.tf
```

References go like this: development/appA --calls--> modules/module2 --calls--> modules/module1

module2 uses the haproxy provider plugin and another provider plugin. The module code looks like this:

```
## Virtual Machine ##
module "module1" {
  source = "../module1"
  vsphere = {
    datacenter_cluster        = var.vsphere.datacenter_cluster
    compute_cluster_name      = var.vsphere.compute_cluster_name
    datastore                 = var.vsphere.datastore
    content_library           = var.vsphere.content_library
    content_library_item_name = var.vsphere.content_library_item_name
    network_name              = var.vsphere.network_name
  }
  virtual_machine = {
    host_name             = var.virtual_machine.host_name
    ipv4_address          = var.virtual_machine.ipv4_address
    ipv4_gateway          = var.virtual_machine.ipv4_gateway
    ipv4_netmask          = var.virtual_machine.ipv4_netmask
    dns_server_list       = var.virtual_machine.dns_server_list
    dns_suffix_list       = var.virtual_machine.dns_suffix_list
    is_windows_image      = true
    domain                = var.virtual_machine.domain
    domain_admin_user     = var.domain_join_username
    domain_admin_password = var.dmz_domain_join_password
  }
}

## Octopus Deploy ##
data "octopusdeploy_environments" "environments" {
  ids = var.octopusdeploy_environments
}
data "octopusdeploy_space" "default" {
  name = var.octopusdeploy_space_name
}
data "octopusdeploy_machine_policies" "default" {
  ids      = var.octopusdeploy_machine_policies
  space_id = data.octopusdeploy_space.default.id
}
resource "octopusdeploy_listening_tentacle_deployment_target" "example" {
  environments = [for e in data.octopusdeploy_environments.environments.environments : e.name]
  is_disabled  = false
  name         = var.name
  roles        = var.octopusdeploy_target_roles
  tentacle_url = "https://${var.name}:10933/"
  thumbprint   = var.octopusdeploy_server_thumbprint
}

## HAProxy ##
data "haproxy_backend" "backend" {
  name = var.haproxy_backend_name
}
resource "haproxy_server" "server" {
  name        = "{{ var.virtual_machine.host_name }}.{{ var.virtual_machine.domain }}"
  port        = 443
  address     = var.virtual_machine.ipv4_address
  parent_name = data.haproxy_backend.backend.id
  parent_type = "backend"
  check       = true
  inter       = 2000
  rise        = 5
  fall        = 2
  depends_on  = [data.haproxy_backend.backend]
}
```

The calling module looks like this:

```
provider "vsphere" {
  user           = var.vsphere_username
  password       = sensitive(var.vsphere_password)
  vsphere_server = var.vsphere_server
}
provider "octopusdeploy" {
  address = var.octopusdeploy_address
  api_key = var.octopusdeploy_api_key
}
provider "haproxy" {
  url      = "https://example.internal"
  username = var.haproxy_dataplane_username
  password = var.haproxy_dataplane_password
}

locals {
  instances = tomap({
    server01 : "xxx.xxx.xxx.xxx",
    server02 : "xxx.xxx.xxx.xxx"
  })
  domain                            = "domain"
  ipv4_gateway                      = "xxx.xxx.xxx.xxx"
  ipv4_netmask                      = 24
  dns_server_list                   = ["xxx.xxx.xxx.xxx"]
  dns_suffix_list                   = ["suffix1"]
  vsphere_datacenter_cluster        = "datacenter cluster"
  vsphere_compute_cluster_name      = "datacenter cluster"
  vsphere_resource_pool_name        = "datacenter cluster/resources"
  vsphere_datastore                 = "datastore"
  vsphere_content_library_item_name = "win-2022-std-core"
  vsphere_network_name              = "Network-Dev"
  octopusdeploy_target_roles = [
    "role1"
  ]
}

module "web_servers" {
  source = "../../modules/web_servers"
  providers = {
    octopusdeploy = octopusdeploy
    haproxy       = haproxy
  }
  for_each = local.instances
  vsphere = {
    datacenter_cluster        = var.vsphere_datacenter_cluster
    compute_cluster_name      = local.vsphere_compute_cluster_name
    datastore                 = local.vsphere_datastore
    content_library           = var.vsphere_content_library
    content_library_item_name = local.vsphere_content_library_item_name
    network_name              = local.vsphere_network_name
  }
  virtual_machine = {
    host_name             = each.key
    ipv4_address          = each.value
    ipv4_gateway          = local.ipv4_gateway
    ipv4_netmask          = local.ipv4_netmask
    dns_server_list       = local.dns_server_list
    dns_suffix_list       = local.dns_suffix_list
    is_windows_image      = true
    domain                = local.domain
    domain_admin_user     = var.domain_join_username
    domain_admin_password = var.sredmz_domain_join_password
  }
  octopusdeploy_server_thumbprint = var.octopusdeploy_server_thumbprint
  octopusdeploy_environments      = var.octopusdeploy_environments
  octopusdeploy_machine_policies  = var.octopusdeploy_machine_policy_ids
  octopusdeploy_space_name        = var.octopusdeploy_space_name
  name                            = "${each.key}.${local.domain}"
  octopusdeploy_target_roles      = local.octopusdeploy_target_roles
  haproxy_backend_name            = "some_443-backend"
}
```

### Steps to Reproduce

Create setup similar to above to use the haproxy provider plugin.

**Expected behavior:** Server "server01.domain" to be added to "some_443-backend" in HAProxy.

**Actual behavior:** Plugin crashes with following error:

```
│ Error: Plugin did not respond
│ 
│   with module.module2["server01"].data.haproxy_backend.backend,
│   on ../../modules/module2/providers.tf line 47, in data "haproxy_backend" "backend":
│   47: data "haproxy_backend" "backend" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs
│ may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.module2["server02"].data.haproxy_backend.backend,
│   on ../../modules/module2/providers.tf line 47, in data "haproxy_backend" "backend":
│   47: data "haproxy_backend" "backend" {
│ 
│ The plugin.(*GRPCProvider).ReadDataSource request was cancelled.
╵

Stack trace from the terraform-provider-haproxy_v0.0.7 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x104ce49dc]

goroutine 56 [running]:
terraform-provider-haproxy/internal/backend.dataSourceHaproxyABackendRead(0x1400010f5f0?, {0x1050a1780?, 0x14000138b70})
        terraform-provider-haproxy/internal/backend/data_source.go:37 +0x10c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ReadDataApply(0x1400048be00, 0x1400010f530?, {0x1050a1780, 0x14000138b70})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:413 +0x5c
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).ReadDataApply(0x14000518680, 0x1400053b9a0, 0x1050a1780?)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:451 +0x60
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadDataSource(0x1400000ef80, {0x140002c7c40?, 0x1400049cc40?}, 0x140002c7c40)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:1046 +0x29c
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadDataSource_Handler({0x1051c1140?, 0x1400000ef80}, {0x10520bbb0, 0x14000139470}, 0x1400049cc40, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3341 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000338000, {0x105210920, 0x14000103380}, 0x1400021a000, 0x140004a3e00, 0x1058ba3d0, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1337 +0xc90
google.golang.org/grpc.(*Server).handleStream(0x14000338000, {0x105210920, 0x14000103380}, 0x1400021a000, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1714 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.0/server.go:959 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.0/server.go:957 +0x16c

Error: The terraform-provider-haproxy_v0.0.7 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

Terraform v1.7.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/vsphere v2.6.1
+ provider registry.terraform.io/octopusdeploylabs/octopusdeploy v0.14.9
+ provider registry.terraform.io/sepehrimanian/haproxy v0.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by SepehrImanian** [comment]
Hi, Thank you for taking the time to report this issue, Did you create "haproxy_backend" terraform resource first ?


for example like this:
```
resource "haproxy_backend" "backend" {
  name  = ...
  mode  = "tcp"
  balance {
    algorithm = "..."
  }
}
```

```
data "haproxy_backend" "backend" {
  name = var.haproxy_backend_name
}
```

the err is:
```
with module.module2["server02"].data.haproxy_backend.backend,
│   on ../../modules/module2/providers.tf line 47, in data "haproxy_backend" "backend":
│   47: data "haproxy_backend" "backend" {
```

It's possible that the 'haproxy_backend' doesn't exist.

@KiyoIchikawa

**Comment by KiyoIchikawa** [comment]
I'm glad I can help out, thank you for creating this provider! We appreciate your time on this.

The "haproxy_backend" is not managed by Terraform and does exist in the HAProxy instance given to the provider. We are hoping to manage the base HAProxy configuration via a different tool and insert servers into pre-existing backends (not managed by Terraform) as the servers are created by Terraform.

**Comment by framegrace** [comment]
Same issue here, just creating a simple backend:
```
Terraform will perform the following actions:

  # haproxy_backend.master_controlplane will be created
  + resource "haproxy_backend" "master_controlplane" {
      + check_cache          = true
      + check_timeout        = 10
      + connect_timeout      = 10
      + http_connection_mode = "http-keep-alive"
      + id                   = (known after apply)
      + mode                 = "http"
      + name                 = "master-api"
      + queue_timeout        = 10
      + server_timeout       = 9

      + balance {
          + algorithm = "roundrobin"
        }

      + forwardfor {
          + enabled = false
        }

      + httpchk_params {
          + method  = "GET"
          + uri     = "/health"
          + version = "HTTP/1.1"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

haproxy_backend.master_controlplane: Creating...
╷
│ Error: Plugin did not respond
│
│   with haproxy_backend.master_controlplane,
│   on main.tf line 140, in resource "haproxy_backend" "master_controlplane":
│  140: resource "haproxy_backend" "master_controlplane" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-haproxy_v0.0.7 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xdd405a]

goroutine 57 [running]:
terraform-provider-haproxy/internal/backend.resourceHaproxyBackendCreate(0xc00080f340, {0xf83980?, 0xc0007993b0})
        terraform-provider-haproxy/internal/backend/resource.go:247 +0xa9a
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0003900a0, 0xc00098afa0, 0xc000810ee0, {0xf83980, 0xc0007993b0})
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:320 +0x438
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000713480, 0xc000173908, 0x10e613b?, 0xf?)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0000127c0, {0xc00080ed90?, 0x497a26?}, 0xc00080ed90)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x805
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10a0f20?, 0xc0000127c0}, {0x12f4210, 0xc0009911a0}, 0xc00080ed20, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000276000, {0x12f8fc0, 0xc000144b60}, 0xc0009939e0, 0xc0002781b0, 0x19c1460, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1337 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc000276000, {0x12f8fc0, 0xc000144b60}, 0xc0009939e0, 0x0)
        google.golang.org/grpc@v1.56.0/server.go:1714 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.56.0/server.go:959 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.56.0/server.go:957 +0x18c

Error: The terraform-provider-haproxy_v0.0.7 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

haproxy+dataplane running on docker:  tried with versions 3.1 and 2.9
haproxy plugin version: 0.0.7  (linux+amd64)
terraform: 1.9.8
provider config:
provider "haproxy" {
  url      = "http://127.0.0.1:5555"
  username = "admin"
  password = var.haproxy_password
}
Dataplane works creating backends with curl from the host, no problem at all.

**Comment by framegrace** [comment]
Seems it fails because we are using dataplane v3?
Looking at the code, the urls use /v2/ everywhere.

**Comment by raspbeguy** [comment]
I can confirm the bug.
